title: Cloud Native Data Platform
baseurl: https://appscode.com
languageCode: en-us
assetDir: static
googleAnalytics: UA-62096468-4
disableKinds:
- taxonomy
- taxonomyTerm
params:
  domain_appscode: https://appscode.com
  domain_guard: https://kubeguard.dev
  domain_configsyncer: https://config-syncer.com
  domain_gateway: https://gateway.voyagermesh.com
  domain_voyagermesh: https://voyagermesh.com
  domain_stash: https://stash.run
  domain_kubestash: https://kubestash.com
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeform: https://kubeform.com
  domain_pharmer: https://pharmer.dev
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://appscode.com
  domain_marketplace: https://marketplace.appscode.com
  search_engine_ID: 015199383701854252104:jccvu4eiulw
  search_api_key: 8fd610038d901dd16a111e6f1568343bb969b084a1952dafdcb1545fd8c35e96
  blog_url: https://appscode.com/blog
  slack_url: https://slack.appscode.com
  github_url: https://github.com/appscode
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  learn_url: https://appscode.com/learn
  docs_url: https://appscode.com/docs
markup:
  goldmark:
    renderer:
      unsafe: true
